In [4]:
# Define functions 

# Define save CSV
def save_csv(data, filename):
    """
    :param csv_inputs:
    :return:
    """
    try:
        with open(filename, "w", encoding='utf-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerows(data)
    except Exception as e:
        print(str(e))
        print("File {} not found or format is wrong".format(filename))

In [5]:
# Install a pip comtradeapicall package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install --upgrade comtradeapicall

Requirement already satisfied: comtradeapicall in /Users/oliverlysaght/anaconda3/lib/python3.10/site-packages (1.0.20)

In [6]:
# Install a pip pandas package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in /Users/oliverlysaght/anaconda3/lib/python3.10/site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/oliverlysaght/anaconda3/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/oliverlysaght/anaconda3/lib/python3.10/site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in /Users/oliverlysaght/anaconda3/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /Users/oliverlysaght/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [7]:
# Import libraries
import pandas
import requests
import comtradeapicall

In [8]:
# Set variables
from datetime import date
from datetime import timedelta
today = date.today()
yesterday = today - timedelta(days=1)
lastweek = today - timedelta(days=7)

In [9]:
# Set subscription key and directory
subscription_key = 'c5fed294c36c4a38b61f6da8eaf24fc2' # comtrade api subscription key (from comtradedeveloper.un.org)
directory = '<OUTPUT DIR>'  # output directory for downloaded files

In [ ]:
# Call get data API to a data frame, max to 250K records, subscription key required

In [15]:
mydf = comtradeapicall.getFinalData(subscription_key,
                                    # Type of trade: C for commodities and S for service
                                    typeCode='C',
                                    # Trade frequency: A for annual and M for monthly
                                    freqCode='A',
                                    # Trade (IMTS) classifications: HS, SITC, BEC or EBOPS.
                                    clCode='HS', 
                                    # Year or month. Year should be 4 digit year. Month should be six digit integer with the values of the form YYYYMM
                                    period='1995',
                                    # Reporter code (Possible values are M49 code of the countries separated by comma (,))
                                    reporterCode='826',
                                    # Commodity code. Multi value input should be in the form of csv (Codes separated by comma (,))
                                    cmdCode='26',
                                    # Trade flow code. Multi value input should be in the form of csv (Codes separated by comma (,))
                                    flowCode='M',
                                    # Partner code (Possible values are M49 code of the countries separated by comma (,))
                                    partnerCode=None,
                                    partner2Code=None,
                                    # Customs code. Multi value input should be in the form of csv (Codes separated by comma (,))
                                    customsCode=None, 
                                    motCode=None,
                                    # Output format
                                    format_output='JSON',
                                    # Add parameters in csv list on which you want the results to be aggregated
                                    aggregateBy=None,
                                    # Mode to choose from
                                    breakdownMode='classic',
                                    countOnly=None,
                                    # Include description
                                    includeDesc=True)

In [16]:
# Look at head of data
mydf.head(5)

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,19950101,1995,52,1995,826,GBR,United Kingdom,M,...,None,False,None,False,1.313138e+09,None,1.313138e+09,0,True,False
1,C,A,19950101,1995,52,1995,826,GBR,United Kingdom,M,...,None,False,None,False,1.645328e+06,None,1.645328e+06,0,True,False
2,C,A,19950101,1995,52,1995,826,GBR,United Kingdom,M,...,None,False,None,False,2.560453e+08,None,2.560453e+08,0,True,False
3,C,A,19950101,1995,52,1995,826,GBR,United Kingdom,M,...,None,False,None,False,3.037612e+06,None,3.037612e+06,0,True,False
4,C,A,19950101,1995,52,1995,826,GBR,United Kingdom,M,...,None,False,None,False,3.459747e+07,None,3.459747e+07,0,True,False

In [ ]:
# Save results to CSV file
mydf.to_csv('comtrade_api.csv')